stages:
  - validate
  - test
  - build-dev
  - dev-deploy
  - build-prod
  - prod-deploy
  - build-preprod
  - preprod-deploy
  - trivy

builderrors:
  stage: validate
  allow_failure: true
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/gramener/builderrors:3.0.2
  script: builderrors > "$CI_PROJECT_DIR/build-error.log"
  artifacts:
    when: always
    paths:
      - build-error.log
    name: "builderrors.log"
    expire_in: 1 week

container_scanning:
  stage: trivy
  image:
    name: docker.io/aquasec/trivy:latest
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
    TRIVY_USERNAME: "clone_token"
    TRIVY_PASSWORD: "$CI_BUILD_TOKEN"
    TRIVY_AUTH_URL: "$CI_REGISTRY"
    FULL_IMAGE_NAME: "$CI_REGISTRY_IMAGE:latest"
  script:
    - trivy --version
    - mkdir -p $CI_PROJECT_DIR/reports
    - time trivy image --exit-code 0 --cache-dir .trivycache/ --no-progress --format template --template "@/contrib/gitlab.tpl" --output "$CI_PROJECT_DIR/reports/gl-container-scanning-report.log" "$FULL_IMAGE_NAME"
    - time trivy image --exit-code 0 --cache-dir .trivycache/ --severity CRITICAL --no-progress "$FULL_IMAGE_NAME"
  cache:
    paths:
      - .trivycache/
  artifacts:
    when: always
    paths:
      - reports/gl-container-scanning-report.log
    reports:
      container_scanning: reports/gl-container-scanning-report.log
    expire_in: 1 week
    name: "trivy.log"
  only:
    - main

build-dev:
  stage: build-dev
  image: docker:latest
  services:
    - name: docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker build  -t $CI_REGISTRY_IMAGE:$(date +%Y.%m.%d.%H) .
    - docker push $CI_REGISTRY_IMAGE:$(date +%Y.%m.%d.%H)
    - docker tag $CI_REGISTRY_IMAGE:$(date +%Y.%m.%d.%H) $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main

variables:
  DEV_SERVER_1: 172.24.1.90
dev-deploy:
  stage: dev-deploy
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    # ssh conf
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
  script:
    - ssh -o stricthostkeychecking=no ubuntu@${DEV_SERVER_1} "sudo docker login -u clone_token -p "YANkxZ4_imRoBZSidzuL" registry.gitlab.renewbuy.in && cd /home/ubuntu/repos/renewbuy_insurance && sh deploy.sh "
  only: 
    - main

build-prod:
  stage: build-prod
  image: docker:latest
  services:
    - name: docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker build -f DockerfileProd -t $CI_REGISTRY_IMAGE:$(date +%Y.%m.%d.%H) .
    - docker push $CI_REGISTRY_IMAGE:$(date +%Y.%m.%d.%H)
    - docker tag $CI_REGISTRY_IMAGE:$(date +%Y.%m.%d.%H) $CI_REGISTRY_IMAGE:prod-latest
    - docker push $CI_REGISTRY_IMAGE:prod-latest
  only:
    - tags

prod-deploy:
  stage: prod-deploy
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    # ssh conf
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
  script:
    - ssh -o stricthostkeychecking=no ubuntu@${PROD_SERVER_IP} "sudo docker login -u clone_token -p "YANkxZ4_imRoBZSidzuL" registry.gitlab.renewbuy.in && cd /home/ubuntu/repos/renewbuy_insurance && sh deploy.sh "
  only: 
    - tags

build-preprod:
  stage: build-preprod
  image: docker:latest
  services:
    - name: docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker build -f DockerfilePreProd -t $CI_REGISTRY_IMAGE:preprod .
    - docker push $CI_REGISTRY_IMAGE:preprod
  only:
    - preprod

preprod-deploy:
  stage: preprod-deploy
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    # ssh conf
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
  script:
    - ssh -o stricthostkeychecking=no ubuntu@${PROD_SERVER_IP} "sudo docker login -u clone_token -p "YANkxZ4_imRoBZSidzuL" registry.gitlab.renewbuy.in && cd /home/ubuntu/repos/renewbuy-insurance-preprod/ && sh deploy.sh "
  only: 
    - preprod

include:
  - template: Jobs/SAST.gitlab-ci.yml
