server {
    listen       80;
    listen  [::]:80;
    #server_name  localhost;
    server_name  _;
    #access_log  /var/log/nginx/host.access.log  main;
    client_max_body_size 40M;
    # kill cache
    add_header Last-Modified $date_gmt;
    add_header Cache-Control 'no-store, no-cache';
    if_modified_since off;
    expires off;
    etag off;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # angular app - all routes will point to index.html
        try_files $uri $uri/ /index.html;
        client_max_body_size 10M;
        expires -1;
    }

    #error_page 404/404.html;
    # redirect server error pages to the static page /50x.html
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
        expires -1;
    }
}
